if mods["Krastorio2"] then-- A RECIPE FOR STAY IN THIS FILE SHOULD HAVE PRODUCTS THAT IS ONLY TOOLS

data:extend ({
  {
    type = "recipe",
    name = "blank-tech-cardv10",
    hide_from_player_crafting = true,
    category = "science-packs-10-crafting",
    enabled = true,
    energy_required = 1.95,
    allow_productivity = true,
    ingredients = {
      { "iron-plate", 20 },
      { "copper-cable", 20 },
    },
    result = "blank-tech-card",
    result_count = 50,
  },
  {
    type = "recipe",
    name = "biters-research-datav10",
    energy_required = 38,
    hide_from_player_crafting = true,
    category = "science-packs-10-crafting",
    enabled = true,
    allow_productivity = true,
    ingredients = {
      { "biomass", 100 },
      { "coke", 50 },
      { "steel-plate", 50 },
    },
    result = "biters-research-data",
    result_count = 50,
  },
  {
    type = "recipe",
    name = "basic-tech-cardv10",
    energy_required = 20,
    hide_from_player_crafting = true,
    category = "science-packs-10-crafting",
    enabled = true,
    allow_productivity = true,
    ingredients = {
      { "wood", 50 },
      { "copper-cable", 50 },
    },
    result = "basic-tech-card",
    result_count = 50,
  },
  {
    type = "recipe",
    name = "space-science-packv10",
    category = "t3-tech-cards",
    energy_required = 20,
    hide_from_player_crafting = true,
    category = "science-packs-10-crafting",
    enabled = true,
    allow_productivity = true,
    ingredients = {
      { "blank-tech-card", 100 },
      { "space-research-data", 50 },
    },
    result = "space-science-pack",
    result_count = 50,
  },
  {
    type = "recipe",
    name = "matter-research-datav10",
    category = "t3-tech-cards",
    energy_required = 20,
    hide_from_player_crafting = true,
    category = "science-packs-10-crafting",
    enabled = true,
    allow_productivity = true,
    ingredients = {
      { "imersite-crystal", 50 },
      { "rare-metals", 50 },
      { "lithium", 50 },
      { "plastic-bar", 50 },
    },
    result = "matter-research-data",
    result_count = 50,
  },
  {
    type = "recipe",
    name = "matter-tech-cardv10",
    category = "t3-tech-cards",
    energy_required = 20,
    hide_from_player_crafting = true,
    category = "science-packs-10-crafting",
    enabled = true,
    allow_productivity = true,
    ingredients = {
      { "blank-tech-card", 150 },
      { "matter-research-data", 50 },
      { "processing-unit", 50 },
    },
    result = "matter-tech-card",
    result_count = 50,
  },
  {
    type = "recipe",
    name = "advanced-tech-cardv10",
    category = "t3-tech-cards",
    energy_required = 20,
    hide_from_player_crafting = true,
    category = "science-packs-10-crafting",
    enabled = true,
    allow_productivity = true,
    ingredients = {
      { "blank-tech-card", 150 },
      { "imersium-gear-wheel", 200 },
      { "lithium-sulfur-battery", 100 },
      { "electric-engine-unit", 50 },
    },
    result = "advanced-tech-card",
    result_count = 50,
  },
  {
    type = "recipe",
    name = "singularity-tech-cardv10",
    category = "t3-tech-cards",
    energy_required = 20,
    hide_from_player_crafting = true,
    category = "science-packs-10-crafting",
    enabled = true,
    allow_productivity = true,
    ingredients = {
      { "blank-tech-card", 150 },
      { "charged-matter-stabilizer", 50 },
      { "ai-core", 50 },
    },
    result = "singularity-tech-card",
    result_count = 50,
  },
  {
    type = "recipe",
    name = "blank-tech-card",
    energy_required = 2,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "iron-plate", 2 },
      { "copper-cable", 2 },
    },
    result = "blank-tech-card",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "biters-research-data",
    energy_required = 40,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "biomass", 10 },
      { "coke", 5 },
      { "steel-plate", 5 },
    },
    result = "biters-research-data",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "basic-tech-card",
    energy_required = 20,
    enabled = true,
    allow_productivity = true,
    ingredients = {
      { "wood", 5 },
      { "copper-cable", 5 },
    },
    result = "basic-tech-card",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "space-science-pack",
    category = "t3-tech-cards",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "blank-tech-card", 10 },
      { "space-research-data", 5 },
    },
    result = "space-science-pack",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "matter-research-data",
    category = "t3-tech-cards",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "imersite-crystal", 5 },
      { "rare-metals", 5 },
      { "lithium", 5 },
      { "plastic-bar", 5 },
    },
    result = "matter-research-data",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "matter-tech-card",
    category = "t3-tech-cards",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "blank-tech-card", 15 },
      { "matter-research-data", 5 },
      { "processing-unit", 5 },
    },
    result = "matter-tech-card",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "advanced-tech-card",
    category = "t3-tech-cards",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "blank-tech-card", 15 },
      { "imersium-gear-wheel", 20 },
      { "lithium-sulfur-battery", 10 },
      { "electric-engine-unit", 5 },
    },
    result = "advanced-tech-card",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "singularity-tech-card",
    category = "t3-tech-cards",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "blank-tech-card", 15 },
      { "charged-matter-stabilizer", 5 },
      { "ai-core", 5 },
    },
    result = "singularity-tech-card",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "blank-tech-card",
    energy_required = 2,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "iron-plate", 2 },
      { "copper-cable", 2 },
    },
    result = "blank-tech-card",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "biters-research-data",
    energy_required = 40,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "biomass", 10 },
      { "coke", 5 },
      { "steel-plate", 5 },
    },
    result = "biters-research-data",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "basic-tech-card",
    energy_required = 20,
    enabled = true,
    allow_productivity = true,
    ingredients = {
      { "wood", 5 },
      { "copper-cable", 5 },
    },
    result = "basic-tech-card",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "space-science-pack",
    category = "t3-tech-cards",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "blank-tech-card", 10 },
      { "space-research-data", 5 },
    },
    result = "space-science-pack",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "matter-research-data",
    category = "t3-tech-cards",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "imersite-crystal", 5 },
      { "rare-metals", 5 },
      { "lithium", 5 },
      { "plastic-bar", 5 },
    },
    result = "matter-research-data",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "matter-tech-card",
    category = "t3-tech-cards",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "blank-tech-card", 15 },
      { "matter-research-data", 5 },
      { "processing-unit", 5 },
    },
    result = "matter-tech-card",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "advanced-tech-card",
    category = "t3-tech-cards",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "blank-tech-card", 15 },
      { "imersium-gear-wheel", 20 },
      { "lithium-sulfur-battery", 10 },
      { "electric-engine-unit", 5 },
    },
    result = "advanced-tech-card",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "singularity-tech-card",
    category = "t3-tech-cards",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "blank-tech-card", 15 },
      { "charged-matter-stabilizer", 5 },
      { "ai-core", 5 },
    },
    result = "singularity-tech-card",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "blank-tech-card",
    energy_required = 2,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "iron-plate", 2 },
      { "copper-cable", 2 },
    },
    result = "blank-tech-card",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "biters-research-data",
    energy_required = 40,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "biomass", 10 },
      { "coke", 5 },
      { "steel-plate", 5 },
    },
    result = "biters-research-data",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "basic-tech-card",
    energy_required = 20,
    enabled = true,
    allow_productivity = true,
    ingredients = {
      { "wood", 5 },
      { "copper-cable", 5 },
    },
    result = "basic-tech-card",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "space-science-pack",
    category = "t3-tech-cards",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "blank-tech-card", 10 },
      { "space-research-data", 5 },
    },
    result = "space-science-pack",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "matter-research-data",
    category = "t3-tech-cards",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "imersite-crystal", 5 },
      { "rare-metals", 5 },
      { "lithium", 5 },
      { "plastic-bar", 5 },
    },
    result = "matter-research-data",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "matter-tech-card",
    category = "t3-tech-cards",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "blank-tech-card", 15 },
      { "matter-research-data", 5 },
      { "processing-unit", 5 },
    },
    result = "matter-tech-card",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "advanced-tech-card",
    category = "t3-tech-cards",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "blank-tech-card", 15 },
      { "imersium-gear-wheel", 20 },
      { "lithium-sulfur-battery", 10 },
      { "electric-engine-unit", 5 },
    },
    result = "advanced-tech-card",
    result_count = 5,
  },
  {
    type = "recipe",
    name = "singularity-tech-card",
    category = "t3-tech-cards",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "blank-tech-card", 15 },
      { "charged-matter-stabilizer", 5 },
      { "ai-core", 5 },
    },
    result = "singularity-tech-card",
    result_count = 5,
  },
})
end