if mods["bobplates"] then
data:extend({
   {
    type = "recipe",
    name = "lead-platex10",
    category = "SX10",
    enabled = true,
    energy_required = 3,
    ingredients = {{ "lead-ore", 1}},
    results = {{"lead-plate", 10}},
    subgroup = "bob-material-smelting",
  },
  {
    type = "recipe",
    name = "tin-platex10",
    category = "SX10",
    enabled = true,
    energy_required = 3,
    ingredients = {{"tin-ore", 10}},
    results = {{"tin-plate", 10}},
  },
  {
    type = "recipe",
    name = "lead-platex100",
    category = "Smelting-X100",
    energy_required = 2.5,
    enabled = true,
    ingredients = {{"lead-ore", 100}},
    results = {{"lead-plate", 100}},
  },
  {
    type = "recipe",
    name = "tin-platex100",
    category = "Smelting-X100",
    energy_required = 2.5,
    enabled = true,
    ingredients = {{"tin-ore", 100}},
    results = {{"tin-plate", 100}},
  },
  {
    type = "recipe",
    name = "lead-platex500",
    category = "SX500",
    energy_required = 2,
    enabled = true,
    ingredients = {{ "lead-ore", 500}},
    results = {{"lead-plate", 500}},
  },
  {
    type = "recipe",
    name = "angelsore1-crushed-smeltingx500",
    category = "SX500",
    energy_required = 2,
    enabled = true,
    ingredients = {{type = "item", name = "angels-ore1-crushed", amount = 1475}},
    results = {{"iron-plate",1000}},
  },
{
    type = "recipe",
    name = "lead-platex1000",
    category = "Smelting1000",
    energy_required = 1,
    enabled = true,
    ingredients = {{ "lead-ore", 1000}},
    results = {{"lead-plate", 1000}},
  },
  {
    type = "recipe",
    name = "angelsore1-crushed-smeltingx1000",
    category = "Smelting1000",
    energy_required = 1,
    enabled = true,
    ingredients = {{type = "item", name = "angels-ore1-crushed", amount = 2900}},
    results = {{"iron-plate",2000}},
  },


})
end