-- data:extend
-- (
-- {
--     {
--     type = "furnace",
--     name = "stone-furnace",
--     icon = "__base__/graphics/icons/stone-furnace.png",
--     icon_size = 64, icon_mipmaps = 4,
--     flags = {"placeable-neutral", "placeable-player", "player-creation"},
--     minable = {mining_time = 0.2, result = "stone-furnace"},
--     max_health = 200,
--     corpse = "stone-furnace-remnants",
--     dying_explosion = "stone-furnace-explosion",
--     repair_sound = sounds.manual_repair,
--     mined_sound = { filename = "__base__/sound/deconstruct-bricks.ogg",volume = 0.8},
--     open_sound = sounds.machine_open,
--     close_sound = sounds.machine_close,
--     vehicle_impact_sound = sounds.car_stone_impact,
--     working_sound =
--     {
--       sound =
--       {
--         {
--           filename = "__base__/sound/furnace.ogg",
--           volume = 0.6
--         }
--       },
--       fade_in_ticks = 4,
--       fade_out_ticks = 20,
--       audible_distance_modifier = 0.4,
--     },
--     resistances =
--     {
--       {
--         type = "fire",
--         percent = 99
--       },
--       {
--         type = "explosion",
--         percent = 30
--       },
--       {
--         type = "impact",
--         percent = 99
--       }
--     },
--     collision_box = {{-0.7, -0.7}, {0.7, 0.7}},
--     selection_box = {{-0.8, -1}, {0.8, 1}},
--     damaged_trigger_effect = hit_effects.rock(),
--     crafting_categories = {"smelting",SX10},
--     result_inventory_size = 1,
--     energy_usage = "1000kW",
    
--     crafting_speed = 2.25,
--     source_inventory_size = 1,
--     energy_source =
--     {
--       type = "burner",
--       fuel_category = "chemical",
--       effectivity = 1,
--       fuel_inventory_size = 1,
--       emissions_per_minute = 30,
--       smoke =
--       {
--         {
--           name = "smoke",
--           deviation = {0.1, 0.1},
--           frequency = 5,
--           position = {0.0, -0.8},
--           starting_vertical_speed = 0.08,
--           starting_frame_deviation = 60
--         }
--       }
--     },
--     animation =
--     {
--       layers =
--       {
--         {
--           filename = "__base__/graphics/entity/stone-furnace/stone-furnace.png",
--           priority = "extra-high",
--           width = 81,
--           height = 64,
--           frame_count = 1,
--           shift = util.by_pixel(14.5, 2),
--           hr_version =
--           {
--             filename = "__base__/graphics/entity/stone-furnace/hr-stone-furnace.png",
--             priority = "extra-high",
--             width = 151,
--             height = 146,
--             frame_count = 1,
--             shift = util.by_pixel(-0.25, 6),
--             scale = 0.5
--           }
--         },
--         {
--           filename = "__base__/graphics/entity/stone-furnace/stone-furnace-shadow.png",
--           priority = "extra-high",
--           width = 81,
--           height = 64,
--           frame_count = 1,
--           draw_as_shadow = true,
--           shift = util.by_pixel(14.5, 2),
--           hr_version =
--           {
--             filename = "__base__/graphics/entity/stone-furnace/hr-stone-furnace-shadow.png",
--             priority = "extra-high",
--             width = 164,
--             height = 74,
--             frame_count = 1,
--             draw_as_shadow = true,
--             shift = util.by_pixel(14.5, 13),
--             scale = 0.5
--           }
--         }
--       }
--     },
--     working_visualisations =
--     {
--       {
--         north_position = {0.0, 0.0},
--         east_position = {0.0, 0.0},
--         south_position = {0.0, 0.0},
--         west_position = {0.0, 0.0},
--         animation =
--         {
--           filename = "__base__/graphics/entity/stone-furnace/stone-furnace-fire.png",
--           priority = "extra-high",
--           line_length = 8,
--           width = 20,
--           height = 49,
--           frame_count = 48,
--           axially_symmetrical = false,
--           direction_count = 1,
--           shift = util.by_pixel(-0.5, 5.5),
--           hr_version =
--           {
--             filename = "__base__/graphics/entity/stone-furnace/hr-stone-furnace-fire.png",
--             priority = "extra-high",
--             line_length = 8,
--             width = 41,
--             height = 100,
--             frame_count = 48,
--             axially_symmetrical = false,
--             direction_count = 1,
--             shift = util.by_pixel(-0.75, 5.5),
--             scale = 0.5
--           }
--         },
--         light = {intensity = 1, size = 1, color = {r=1.0, g=1.0, b=1.0}}
--       }
--     },
--     --fast_replaceable_group = "furnace",
--     --next_upgrade = "steel-furnace",
--     water_reflection =
--     {
--       pictures =
--       {
--         filename = "__base__/graphics/entity/stone-furnace/stone-furnace-reflection.png",
--         priority = "extra-high",
--         width = 16,
--         height = 16,
--         shift = util.by_pixel(0, 35),
--         variation_count = 1,
--         scale = 5,
--       },
--       rotate = false,
--       orientation_to_variation = false
--     }
--   },
 


-- }
-- )