if mods["space-exploration"] then
local data_util = require("data_util")
--local RecipeTints = require("prototypes/recipe-tints")
local make_recipe = data_util.make_recipe
local recipe_amount = 10




data_util.allow_productivity
({
data_util.mod_prefix .. "molten-iron",
--data_util.mod_prefix .. "casting-iron-plate",
data_util.mod_prefix .. "molten-copper",
--data_util.mod_prefix .. "casting-copper-plate",
data_util.mod_prefix .. "molten-holmium",
data_util.mod_prefix .. "molten-beryllium",
--data_util.mod_prefix .. "holmium-ingot",
--data_util.mod_prefix .. "holmium-plate",
--data_util.mod_prefix .. "holmium-ingot-no-vulcanite",
data_util.mod_prefix .. "iridium-ingot",
--data_util.mod_prefix .. "iridium-plate",
--data_util.mod_prefix .. "beryllium-ingot",
--data_util.mod_prefix .. "beryllium-plate",
--data_util.mod_prefix .. "beryllium-ingot-no-vulcanite",
data_util.mod_prefix .. "naquium-ingot",
--data_util.mod_prefix .. "naquium-plate",
data_util.mod_prefix .. "stone-brick-vulcanite",
data_util.mod_prefix .. "glass-vulcanite",
  "utility-science-pack",
  "production-science-pack",
  "space-science-pack",
  data_util.mod_prefix .. "rocket-science-pack",
  data_util.mod_prefix .. "cargo-rocket-section",
  data_util.mod_prefix .. "cargo-rocket-section-beryllium",
  data_util.mod_prefix .. "cargo-rocket-cargo-pod",
  data_util.mod_prefix .. "cargo-rocket-fuel-tank",
  data_util.mod_prefix .. "cryonite-crushedx10",
  data_util.mod_prefix .. "cryonite-washedx10",
  data_util.mod_prefix .. "cryonite-powderx10",
  data_util.mod_prefix .. "cryonite-crystalx10",
  data_util.mod_prefix .. "cryonite-rodx10",
  data_util.mod_prefix .. "cryonite-slushx10",
  data_util.mod_prefix .. "cryonite-ion-exchange-beadsx10",
  data_util.mod_prefix .. "beryllium-ore-crushedx10",
  data_util.mod_prefix .. "beryllium-ore-washedx10",
  data_util.mod_prefix .. "beryllium-sulfatex10",
  data_util.mod_prefix .. "beryllium-hydroxidex10",
  data_util.mod_prefix .. "beryllium-powderx10",
  data_util.mod_prefix .. "holmium-ore-crushedx10",
  data_util.mod_prefix .. "holmium-ore-washedx10",
  data_util.mod_prefix .. "holmium-chloridex10",
  data_util.mod_prefix .. "holmium-powderx10",
  data_util.mod_prefix .. "iridium-ore-crushedx10",
  data_util.mod_prefix .. "iridium-ore-washedx10",
  data_util.mod_prefix .. "iridium-powderx10",
  data_util.mod_prefix .. "iridium-blastcakex10",
  data_util.mod_prefix .. "naquium-ore-crushedx10",
  data_util.mod_prefix .. "naquium-ore-washedx10",
  data_util.mod_prefix .. "naquium-crystalx10",
  data_util.mod_prefix .. "naquium-refinedx10",
  data_util.mod_prefix .. "naquium-powderx10",
  data_util.mod_prefix .. "vitamelange-nuggetx10",
  data_util.mod_prefix .. "vitamelange-roastx10",
  data_util.mod_prefix .. "vitamelange-bloomx10",
  data_util.mod_prefix .. "vitamelange-spicex10",
  data_util.mod_prefix .. "vitamelange-extractx10",
  data_util.mod_prefix .. "vulcanite-crushedx10",
  data_util.mod_prefix .. "vulcanite-washedx10",
  data_util.mod_prefix .. "vulcanite-enrichedx10",
  data_util.mod_prefix .. "vulcanite-blockx10",
  data_util.mod_prefix .. "vulcanite-ion-exchange-beadsx10",
  data_util.mod_prefix .. "vulcanite-rocket-fuelx10",
  data_util.mod_prefix .. "aeroframe-polex10",
  data_util.mod_prefix .. "aeroframe-scaffoldx10",
  data_util.mod_prefix .. "aeroframe-bulkheadx10",
  data_util.mod_prefix .. "lattice-pressure-vesselx10",
  data_util.mod_prefix .. "heavy-girderx10",
  data_util.mod_prefix .. "heavy-bearingx10",
  data_util.mod_prefix .. "heavy-compositex10",
  data_util.mod_prefix .. "heavy-assemblyx10",
  data_util.mod_prefix .. "vitalic-acidx10",
  data_util.mod_prefix .. "bioscrubberx10",
  data_util.mod_prefix .. "vitalic-reagentx10",
  data_util.mod_prefix .. "vitalic-epoxyx10",
  data_util.mod_prefix .. "self-sealing-gelx10",
  data_util.mod_prefix .. "holmium-cablex10",
  data_util.mod_prefix .. "holmium-solenoidx10",
  data_util.mod_prefix .. "quantum-processorx10",
  data_util.mod_prefix .. "dynamic-emitterx10",
  data_util.mod_prefix .. "cryonite-lubricantx10",
  data_util.mod_prefix .. "heat-shielding-iridiumx10",
  data_util.mod_prefix .. "pulverised-sandx10",
  data_util.mod_prefix .. "low-density-structure-beryllium",
  data_util.mod_prefix .. "processing-unit-holmiumx10",
  data_util.mod_prefix .. "space-probe-rocket",
  data_util.mod_prefix .. "space-elevator-cable",
  data_util.mod_prefix .. "space-elevator-cable-nano",
  data_util.mod_prefix .. "pyrofluxx10"

})
data_util.allow_productivity("sand-from-stonex10")
data_util.allow_productivity("glass-from-sandx10")
data_util.allow_productivity("sand-to-solid-sandx10")
data_util.allow_productivity(data_util.mod_prefix .. "heat-shieldingx10")
--data_util.allow_productivity(data_util.mod_prefix .. "rocket-science-pack")
data_util.allow_productivity(data_util.mod_prefix .. "data-storage-substratex10")
data_util.allow_productivity(data_util.mod_prefix .. "material-testing-packx10")

if not data.raw.recipe["sand-from-stone"] then
  data:extend({
    {
      ingredients = {
        { "stone", 1 }
      },
      name = "sand-from-stone",
      result = "sand",
      result_count = 2,
      type = "recipe",
      enabled = false,
      energy_required = 0.5,
    }
  })
end
data:extend({
  {
    ingredients = {
      { "stone", 10 }
    },
    name = "pulverised-sandx10",
    result = "sand",
    result_count = 30,
    type = "recipe",
    enabled = true,
    energy_required = 0.5,
    category = "pulverisingx10",
    --localised_name = {"recipe-name."..data_util.mod_prefix .. "pulverised-sand"},
    always_show_made_in = true,
  }
})

if not data.raw.recipe["glass-from-sand"] then
  data:extend({
    {
      category = "SX10",
      energy_required = 4,
      ingredients = {
        { "sand", 40 }
      },
      name = "glass-from-sandx10",
      result = "glass",
      result_count = 10,
      type = "recipe",
      enabled = true,
    },
  })
end

data:extend({
  
  {
    type = "recipe",
    name = data_util.mod_prefix .. "heat-shielding",
    result = data_util.mod_prefix .. "heat-shielding",
    energy_required = 10,
    ingredients = {
      { name = "stone-tablet", amount = 20},
      { "sulfur", 8 },
      { "steel-plate", 2 }
    },
    requester_paste_multiplier = 2,
    enabled = false,
    always_show_made_in = false,
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "thruster-suit",
    result = data_util.mod_prefix .. "thruster-suit",
    enabled = false,
    energy_required = 30,
    ingredients = {
      { "rocket-control-unit", 10 },
      { data_util.mod_prefix .. "heat-shielding", 20 },
      { "low-density-structure", 20 },
      { "glass", 20 },
      { "jetpack-1", 1 },
      { data_util.mod_prefix .. "lifesupport-equipment-1", 1 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "thruster-suit-2",
    results = {
      { name=data_util.mod_prefix .. "thruster-suit-2", amount = 1},
    },
    main_product = data_util.mod_prefix .. "thruster-suit-2",
    enabled = false,
    energy_required = 30,
    ingredients = {
      { "processing-unit", 50 },
      { "rocket-fuel", 50 },
      { data_util.mod_prefix .. "iridium-plate", 50 },
      { data_util.mod_prefix .. "material-catalogue-1", 1 },
      { data_util.mod_prefix .. "thruster-suit", 1 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "thruster-suit-3",
    results = {
      { name=data_util.mod_prefix .. "thruster-suit-3", amount = 1},
    },
    main_product = data_util.mod_prefix .. "thruster-suit-3",
    enabled = false,
    energy_required = 30,
    ingredients = {
      { "processing-unit", 100 },
      { "rocket-fuel", 50 },
      { data_util.mod_prefix .. "superconductive-cable", 50 },
      { data_util.mod_prefix .. "astronomic-catalogue-1", 1 },
      { data_util.mod_prefix .. "biological-catalogue-1", 1 },
      { data_util.mod_prefix .. "energy-catalogue-3", 1 },
      { data_util.mod_prefix .. "material-catalogue-3", 1 },
      { data_util.mod_prefix .. "aeroframe-bulkhead", 1 },
      { data_util.mod_prefix .. "thruster-suit-2", 1 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "thruster-suit-4",
    results = {
      { name=data_util.mod_prefix .. "thruster-suit-4", amount = 1},
    },
    main_product = data_util.mod_prefix .. "thruster-suit-4",
    enabled = false,
    energy_required = 30,
    ingredients = {
      { "processing-unit", 200 },
      { data_util.mod_prefix .. "antimatter-canister", 10 },
      { data_util.mod_prefix .. "nanomaterial", 200 },
      { data_util.mod_prefix .. "superconductive-cable", 100 },
      { data_util.mod_prefix .. "naquium-plate", 100 },
      { data_util.mod_prefix .. "deep-catalogue-2", 1 },
      { data_util.mod_prefix .. "self-sealing-gel", 1 },
      { data_util.mod_prefix .. "lattice-pressure-vessel", 1 },
      { data_util.mod_prefix .. "naquium-processor", 1 },
      { data_util.mod_prefix .. "thruster-suit-3", 1 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "rtg-equipment",
    result = data_util.mod_prefix .. "rtg-equipment",
    enabled = false,
    energy_required = 10,
    ingredients = {
      { "processing-unit", 50 },
      { "low-density-structure", 50 },
      { "uranium-fuel-cell", 4 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "rtg-equipment-2",
    result = data_util.mod_prefix .. "rtg-equipment-2",
    enabled = false,
    energy_required = 10,
    ingredients = {
      { "processing-unit", 50 },
      { "low-density-structure", 100 },
      { data_util.mod_prefix .."atomic-data", 1 },
      { data_util.mod_prefix .."radiation-data", 1 },
      { data_util.mod_prefix .. "rtg-equipment", 4 },
      { data_util.mod_prefix .. "holmium-solenoid", 8 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "adaptive-armour-equipment-1",
    result = data_util.mod_prefix .. "adaptive-armour-equipment-1",
    enabled = false,
    energy_required = 10,
    ingredients = {
      { "steel-plate", 20 },
      { "advanced-circuit", 10 },
      { "battery", 5 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "adaptive-armour-equipment-2",
    result = data_util.mod_prefix .. "adaptive-armour-equipment-2",
    enabled = false,
    energy_required = 10,
    ingredients = {
      { "steel-plate", 30 },
      { "processing-unit", 10 },
      { "low-density-structure", 10 },
      { data_util.mod_prefix .. "adaptive-armour-equipment-1", 1 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "adaptive-armour-equipment-3",
    result = data_util.mod_prefix .. "adaptive-armour-equipment-3",
    enabled = false,
    energy_required = 10,
    ingredients = {
      { "steel-plate", 40 },
      { "processing-unit", 10 },
      { data_util.mod_prefix .. "heat-shielding", 10 },
      { data_util.mod_prefix .. "adaptive-armour-equipment-2", 1 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "adaptive-armour-equipment-4",
    result = data_util.mod_prefix .. "adaptive-armour-equipment-4",
    enabled = false,
    energy_required = 10,
    ingredients = {
      { "steel-plate", 50 },
      { "processing-unit", 20 },
      { data_util.mod_prefix .. "heat-shielding", 20 },
      { data_util.mod_prefix .. "adaptive-armour-equipment-3", 1 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "adaptive-armour-equipment-5",
    result = data_util.mod_prefix .. "adaptive-armour-equipment-5",
    enabled = false,
    energy_required = 10,
    ingredients = {
      { "steel-plate", 40 },
      { "processing-unit", 30 },
      { data_util.mod_prefix .. "nanomaterial", 10 },
      { data_util.mod_prefix .. "adaptive-armour-equipment-4", 1 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
  },
  {
    type = "recipe",
    name = "energy-shield-mk3-equipment",
    result = "energy-shield-mk3-equipment",
    enabled = false,
    energy_required = 10,
    ingredients = {
      { "energy-shield-mk2-equipment", 5 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
  },
  {
    type = "recipe",
    name = "energy-shield-mk4-equipment",
    result = "energy-shield-mk4-equipment",
    enabled = false,
    energy_required = 10,
    ingredients = {
      { "energy-shield-mk3-equipment", 5 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
  },
  {
    type = "recipe",
    name = "energy-shield-mk5-equipment",
    result = "energy-shield-mk5-equipment",
    enabled = false,
    energy_required = 10,
    ingredients = {
      { "energy-shield-mk4-equipment", 5 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
  },
  {
    type = "recipe",
    name = "energy-shield-mk6-equipment",
    result = "energy-shield-mk6-equipment",
    enabled = false,
    energy_required = 10,
    ingredients = {
      { "energy-shield-mk5-equipment", 5 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
  },




  {
    type = "recipe",
    name = data_util.mod_prefix .. "aeroframe-pole",
    results = {{data_util.mod_prefix .. "aeroframe-pole", 2}},
    energy_required = 1,
    ingredients = {
      { data_util.mod_prefix .. "beryllium-plate", 1 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
    enabled = false,
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "aeroframe-scaffold",
    result = data_util.mod_prefix .. "aeroframe-scaffold",
    energy_required = 2,
    ingredients = {
      { data_util.mod_prefix .. "aeroframe-pole", 2 },
      { data_util.mod_prefix .. "beryllium-plate", 1 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
    enabled = false,
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "aeroframe-bulkhead",
    result = data_util.mod_prefix .. "aeroframe-bulkhead",
    energy_required = 4,
    ingredients = {
      { data_util.mod_prefix .. "aeroframe-scaffold", 1 },
      { "low-density-structure", 1 },
      { data_util.mod_prefix .. "beryllium-plate", 4 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
    enabled = false,
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "lattice-pressure-vessel",
    result = data_util.mod_prefix .. "lattice-pressure-vessel",
    energy_required = 3,
    ingredients = {
      { data_util.mod_prefix .. "beryllium-plate", 5 },
      { data_util.mod_prefix .. "cryonite-rod", 2 },
      { data_util.mod_prefix .. "vulcanite-block", 1 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
    enabled = false,
    category="space-manufacturing"
  },

  {
    type = "recipe",
    name = data_util.mod_prefix .. "heavy-girder",
    result = data_util.mod_prefix .. "heavy-girder",
    energy_required = 1,
    ingredients = {
      { data_util.mod_prefix .. "iridium-plate", 2 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
    enabled = false,
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "heavy-bearing",
    result = data_util.mod_prefix .. "heavy-bearing",
    energy_required = 2,
    ingredients = {
      { data_util.mod_prefix .. "iridium-plate", 4 },
      { type="fluid", name="lubricant", amount=4 },
    },
    category="crafting-with-fluid",
    requester_paste_multiplier = 1,
    always_show_made_in = false,
    enabled = false,
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "heavy-composite",
    result = data_util.mod_prefix .. "heavy-composite",
    energy_required = 3,
    ingredients = {
      { data_util.mod_prefix .. "iridium-plate", 4 },
      { data_util.mod_prefix .. "heavy-girder", 2 },
      { data_util.mod_prefix .. "heat-shielding", 4 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
    enabled = false,
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "heavy-assembly",
    result = data_util.mod_prefix .. "heavy-assembly",
    energy_required = 4,
    ingredients = {
      { data_util.mod_prefix .. "heavy-composite", 2 },
      { data_util.mod_prefix .. "heavy-bearing", 2 },
      { "electric-engine-unit", 2 },
      { type="fluid", name="lubricant", amount=4 },
    },
    category="crafting-with-fluid",
    requester_paste_multiplier = 1,
    always_show_made_in = false,
    enabled = false,
  },


  {
    type = "recipe",
    name = "vitalic-acidx10",
    
    energy_required = 1,
    ingredients = {
      { "glass", 1 },
      { name = data_util.mod_prefix .. "vitamelange-extract", amount = recipe_amount },
      { type = "fluid", name = "sulfuric-acid", amount = 2 },
    },
    results = {
      { type = "fluid", name = data_util.mod_prefix .. "vitalic-acid", amount = 2}
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
    enabled = false,
    allow_productivity = true,
    category = "crafting-with-fluid",
  },
  {
    type = "recipe",
    name = "bioscrubberx10",
    result = data_util.mod_prefix .. "bioscrubber",
    energy_required = 2,
    ingredients = 
    {
      { type = "fluid", name = data_util.mod_prefix .. "vitalic-acid", amount = 2 * recipe_amount},
      {  name = "glass",amount =  recipe_amount },
      {  name = "steel-plate",amount =  recipe_amount },
    },
    --crafting_machine_tint = RecipeTints.vita_tint,
    requester_paste_multiplier = 1,
    always_show_made_in = true,
    enabled = true,
    allow_productivity = true,
    category = "chemistry",
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "vitalic-reagent",
    result = data_util.mod_prefix .. "vitalic-reagent",
    energy_required = 3,
    ingredients = {
      { data_util.mod_prefix .. "vitamelange-extract", 4 },
      { data_util.mod_prefix .. "vulcanite-block", 4 },
    },
    --crafting_machine_tint = RecipeTints.vita_tint,
    requester_paste_multiplier = 1,
    always_show_made_in = true,
    enabled = false,
    allow_productivity = true,
    category = "chemistry",
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "vitalic-epoxy",
    result = data_util.mod_prefix .. "vitalic-epoxy",
    energy_required = 4,
    ingredients = {
      { data_util.mod_prefix .. "vitalic-reagent", 2 },
      { data_util.mod_prefix .. "vitalic-acid", 2 },
      { "sulfur", 4 },
    },
    --crafting_machine_tint = RecipeTints.vita_tint,
    requester_paste_multiplier = 1,
    always_show_made_in = true,
    enabled = false,
    category = "chemistry",
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "self-sealing-gel",
    result = data_util.mod_prefix .. "self-sealing-gel",
    energy_required = 5,
    ingredients = {
      { data_util.mod_prefix .. "vitalic-reagent", 2 },
      { data_util.mod_prefix .. "vitalic-epoxy", 2 },
      { data_util.mod_prefix .. "cryonite-rod", 2 },
    },
    --crafting_machine_tint = RecipeTints.methane_tint,
    requester_paste_multiplier = 1,
    always_show_made_in = true,
    enabled = false,
    category = "space-biochemical",
  },




  {
    type = "recipe",
    name = "holmium-cablex10",
    results = {{data_util.mod_prefix .. "holmium-cable", 20}},
    energy_required = 1,
    ingredients = {
      { data_util.mod_prefix .. "holmium-plate", 10 },
      { "plastic-bar", 10},
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
    enabled = true,
    allow_productivity = true,
    category = "science-packs-10-crafting",
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "holmium-solenoid",
    result = data_util.mod_prefix .. "holmium-solenoid",
    energy_required = 2,
    ingredients = {
      { data_util.mod_prefix .. "holmium-cable", 4 },
      { data_util.mod_prefix .. "holmium-plate", 1 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = false,
    enabled = false,
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "quantum-processor",
    result = data_util.mod_prefix .. "quantum-processor",
    energy_required = 3,
    ingredients = {
      { "processing-unit", 1 },
      { data_util.mod_prefix .. "holmium-cable", 4 },
      { data_util.mod_prefix .. "holmium-plate", 1 },
      {data_util.mod_prefix .. "quantum-phenomenon-data", 1},
    },
    requester_paste_multiplier = 1,
    always_show_made_in = true,
    enabled = false,
    category="space-manufacturing"
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "dynamic-emitter",
    result = data_util.mod_prefix .. "dynamic-emitter",
    energy_required = 4,
    ingredients = {
      { data_util.mod_prefix .. "holmium-solenoid", 1 },
      { data_util.mod_prefix .. "quantum-processor", 1 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = true,
    enabled = false,
    category="space-manufacturing"
  },

  {
    type = "recipe",
    name = data_util.mod_prefix .. "naquium-cube",
    result = data_util.mod_prefix .. "naquium-cube",
    energy_required = 10,
    ingredients = {
      { type="fluid", name = data_util.mod_prefix .. "particle-stream", amount = 16 },
      { data_util.mod_prefix .. "naquium-plate", 16 },
      { data_util.mod_prefix .. "nanomaterial", 1 },
      { data_util.mod_prefix .. "vulcanite-block", 1 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = true,
    enabled = false,
    category = "space-materialisation",
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "naquium-tessaract",
    main_product = data_util.mod_prefix .. "naquium-tessaract",
    energy_required = 20,
    ingredients = {
      { data_util.mod_prefix .. "naquium-cube", 1 },
      { data_util.mod_prefix .. "naquium-plate", 16 },
      { data_util.mod_prefix .. "cryonite-rod", 4 },
      { name = data_util.mod_prefix .. "arcosphere-a", amount = 1},
      { name = data_util.mod_prefix .. "arcosphere-b", amount = 1},
      { name = data_util.mod_prefix .. "arcosphere-c", amount = 1},
    },
    results = {
      { name = data_util.mod_prefix .. "naquium-tessaract", amount = 1},
      { name = data_util.mod_prefix .. "arcosphere-d", amount= 1 },
      { name = data_util.mod_prefix .. "arcosphere-e", amount= 1 },
      { name = data_util.mod_prefix .. "arcosphere-f", amount= 1 },
      { name = data_util.mod_prefix .. "arcosphere-g", amount= 0 },
      { name = data_util.mod_prefix .. "arcosphere-h", amount= 0 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = true,
    enabled = false,
    category = "arcosphere",
    localised_description = {"space-exploration.arcosphere-random"}
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "naquium-tessaract-alt",
    main_product = data_util.mod_prefix .. "naquium-tessaract",
    energy_required = 20,
    ingredients = {
      { data_util.mod_prefix .. "naquium-cube", 1 },
      { data_util.mod_prefix .. "naquium-plate", 16 },
      { data_util.mod_prefix .. "cryonite-rod", 4 },
      { name = data_util.mod_prefix .. "arcosphere-a", amount = 1},
      { name = data_util.mod_prefix .. "arcosphere-b", amount = 1},
      { name = data_util.mod_prefix .. "arcosphere-c", amount = 1},
    },
    results = {
      { name = data_util.mod_prefix .. "naquium-tessaract", amount = 1},
      { name = data_util.mod_prefix .. "arcosphere-d", amount= 0 },
      { name = data_util.mod_prefix .. "arcosphere-e", amount= 0 },
      { name = data_util.mod_prefix .. "arcosphere-f", amount= 1 },
      { name = data_util.mod_prefix .. "arcosphere-g", amount= 1 },
      { name = data_util.mod_prefix .. "arcosphere-h", amount= 1 },
    },
    requester_paste_multiplier = 1,
    always_show_made_in = true,
    enabled = false,
    category = "arcosphere",
    localised_description = {"space-exploration.arcosphere-random"}
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "naquium-processor",
    main_product = data_util.mod_prefix .. "naquium-processor",
    energy_required = 30,
    ingredients = {
      { data_util.mod_prefix .. "quantum-processor", 1 },
      { data_util.mod_prefix .. "naquium-tessaract", 1 },
      { type = "fluid", name = data_util.mod_prefix .. "neural-gel-2", amount = 4},
      { name = data_util.mod_prefix .. "arcosphere-c", amount = 1},
      { name = data_util.mod_prefix .. "arcosphere-d", amount = 1},
      { name = data_util.mod_prefix .. "arcosphere-e", amount = 1},
      { name = data_util.mod_prefix .. "arcosphere-f", amount = 1},
      { name = data_util.mod_prefix .. "arcosphere-g", amount = 1},
      { name = data_util.mod_prefix .. "arcosphere-h", amount = 1},
    },
    results = {
      {name = data_util.mod_prefix .. "naquium-processor", amount = 1},
      { name = data_util.mod_prefix .. "arcosphere-a", amount = 5},
      { name = data_util.mod_prefix .. "arcosphere-b", amount = 1},
    },
    requester_paste_multiplier = 1,
    always_show_made_in = true,
    enabled = false,
    category = "arcosphere",
    localised_description = {"space-exploration.arcosphere-random"}
  },
  {
    type = "recipe",
    name = data_util.mod_prefix .. "naquium-processor-alt",
    main_product = data_util.mod_prefix .. "naquium-processor",
    energy_required = 30,
    ingredients = {
      { data_util.mod_prefix .. "quantum-processor", 1 },
      { data_util.mod_prefix .. "naquium-tessaract", 1 },
      { type = "fluid", name = data_util.mod_prefix .. "neural-gel-2", amount = 4},
      { name = data_util.mod_prefix .. "arcosphere-c", amount = 1},
      { name = data_util.mod_prefix .. "arcosphere-d", amount = 1},
      { name = data_util.mod_prefix .. "arcosphere-e", amount = 1},
      { name = data_util.mod_prefix .. "arcosphere-f", amount = 1},
      { name = data_util.mod_prefix .. "arcosphere-g", amount = 1},
      { name = data_util.mod_prefix .. "arcosphere-h", amount = 1},
    },
    results = {
      {name = data_util.mod_prefix .. "naquium-processor", amount = 1},
      { name = data_util.mod_prefix .. "arcosphere-a", amount = 1},
      { name = data_util.mod_prefix .. "arcosphere-b", amount = 5},
    },
    requester_paste_multiplier = 1,
    always_show_made_in = true,
    enabled = false,
    category = "arcosphere",
    localised_description = {"space-exploration.arcosphere-random"}
  },
})
end